version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - davesnx
  - mackermans
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.2
    - 6.0.0
  - dependency-name: chai
    versions:
    - 4.3.4
  - dependency-name: mocha
    versions:
    - 8.3.2
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.9
