language: node_js
node_js:
  - "6.1"
  - "6"
  - "4.0"
  - "0.12"
branches:
  only:
    - master
after_script:
  - npm run coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/58fc2818df28bc310ab3
      on_success: change  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: false     # default: false
