language: node_js
node_js:
  - "node"
  - "6"
  - "4"

branches:
  only:
    - master

cache: yarn

after_install: npm run lint

after_script:
  - npm run coveralls || true

after_success:
  - curl -Lo travis_after_all.py https://git.io/vLSON
  - python travis_after_all.py
  - npm run semantic-release || true
